# Service and Deployment for alumno-api
apiVersion: v1
kind: Service
metadata:
  name: alumno-api-service
spec:
  type: NodePort
  selector:
    app: alumno-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30072
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: alumno-api-deployment
  labels:
    app: alumno-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alumno-api
  template:
    metadata:
      labels:
        app: alumno-api
    spec:
      containers:
        - name: alumno-api-container
          image: "058264105727.dkr.ecr.us-east-1.amazonaws.com/alumno_api:latest"
          imagePullPolicy: Always
          ports:
            - containerPort: 8080

# Service and Deployment for consumo-api
---
apiVersion: v1
kind: Service
metadata:
  name: consumo-api-service
spec:
  type: NodePort
  selector:
    app: consumo-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30073
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumo-api-deployment
  labels:
    app: consumo-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consumo-api
  template:
    metadata:
      labels:
        app: consumo-api
    spec:
      containers:
        - name: consumo-api-container
          image: "058264105727.dkr.ecr.us-east-1.amazonaws.com/consumo_api"
          imagePullPolicy: Always
          ports:
            - containerPort: 8080

